project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!xxx-template.qmd"

website:
  title: "Modelica & FMI"
  body-footer: | 
    © 2025-2026 Clément Coïc — Licensed under [creative commons 4.0](https://creativecommons.org/licenses/by-nc/4.0/). Non-commercial use only.
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "A bit of context"
        href: 001-Commitment.qmd
      - section: "Modelica"
        contents:
          - text: "Modelica 101"
            href: 002-Modelica101.qmd
          - text: "Your first Modelica model"
            href: 003-FirstModel.qmd
          - text: "Your first Modelica simulation"
            href: 004-FirstSimulation.qmd
          - text: "Your first Modelica model refactoring"
            href: 005-ModelRefactoring.qmd
          - text: "Acausality, the secret service of Modelica"
            href: 007-AcausalityEquation.qmd
          - text: "One model serves several purposes"
            href: 008-AcausalityModels.qmd
          - text: "The need for dynamic simulation"
            href: 009-NeedForDynamicSimulation.qmd
          - text: "What Dynamic Simulation Does?"
            href: 010-WhatDynamicSimulationDoes.qmd
          - text: "Understand your model: let's integrate!"
            href: 011-LetsIntegrate.qmd
          - text: "Choosing your Christmas gift!"
            href: 012-ReplaceableModels.qmd
          - text: "Do you deserve a Christmas present?"
            href: 013-ConditionalModels.qmd
          - text: "A (technical) summary of model variants"
            href: 014-ModelVariants.qmd
          - text: "The different use of models"
            href: 015-ModelUsage.qmd
          - text: "The basic structure of Modelica code"
            href: 017-BasicCode.qmd
          - text: "Enhancing our first Modelica code"
            href: 018-CodeEnhancement.qmd
          - text: "What's inside a connector?"
            href: 020-WhatsInsideAConnector.qmd
          - text: "Stream Connectors"
            href: 021-StreamConnectors.qmd
          - text: "Initialization"
            href: 022-Initialization.qmd
          - text: "Building Your Library"
            href: 023-BuildingYourLibrary.qmd
          - text: "Annotations"
            href: 024-Annotations.qmd
          - text: "Events"
            href: 025-Events.qmd

      - section: "FMI"
        contents:
          - text: "Spreading the word with FMI"
            href: 006-SpreadingWithFMI.qmd
          - text: "Model Exchange vs Co-Simulation FMUs"
            href: 016-MEvsCS.qmd
          - text: "Simulating our FMU with FMPy"
            href: 019-fmpySimulation.qmd
          - text: "Events in FMUs"
            href: 026-EventsInFMUs.qmd
          - text: "FMI 3.0 & FMPy Cheat Sheet"
            href: 027-FMICheatSheet.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



